version: "3.7"
services:

  # PHP-FPM
  php-fpm:
    build: ./.docker/php-fpm
    container_name: ${APP_NAME:?err}-php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@mariadb:3306/${DATABASE_NAME}?serverVersion=5.7
    depends_on:
      - mariadb
    working_dir: /var/www
    volumes:
      - .:/var/www

  # NGINX
  nginx:
    image: nginx:latest
    container_name: ${APP_NAME:?err}-nginx
    ports:
      - 80:80
    depends_on:
      - php-fpm
    volumes:
      - .:/var/www:ro
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro

  # MariaDB
  mariadb:
    image: mariadb:latest
    container_name: ${APP_NAME:?err}-mariadb
    restart: 'on-failure'
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - "./.docker/database/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "mysqldata:/var/lib/mysql"

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8081:80
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb

# Volumes
volumes:
  mysqldata:
